### ISSUE TITLE
execute_debug panic

### ISSUE THREAD

**Issue by nkypy** [jafioti/luminal#44] opened 2024-03-22 09:44 UTC
error output
```bash
------------------------------------------------------------------------------------------------- Executing -------------------------------------------------------------------------------------------------
Constant(0.0).............................................................................................................................................................................................0µs
Constant(1e-6)............................................................................................................................................................................................0µs
Constant(1.442695)........................................................................................................................................................................................0µs
Constant(2.0).............................................................................................................................................................................................0µs
Constant(1e-5)............................................................................................................................................................................................0µs
Constant(2048)............................................................................................................................................................................................0µs
Recip ([])................................................................................................................................................................................................1µs
Tensor Load...............................................................................................................................................................................................0µs
Constant(-1.0)............................................................................................................................................................................................0µs
Constant(1.0).............................................................................................................................................................................................0µs
Contiguous ([65536]).....................................................................................................................................................................................14ms
Contiguous ([131071])....................................................................................................................................................................................26ms
Contiguous ([65536, 131071])thread 'main' panicked at library/alloc/src/raw_vec.rs:25:5:
capacity overflow
```

**Comment by jafioti** [comment] 2024-03-27 19:03
Hmm, does it work for you if you change .execeute_debug to .execute?

**Comment by nkypy** [comment] 2024-03-28 01:24
> Hmm, does it work for you if you change .execeute_debug to .execute?

execute() same as execute_debug()

```bash
thread 'main' panicked at library/alloc/src/raw_vec.rs:25:5:
capacity overflow
```

**Comment by jafioti** [comment] 2024-04-08 14:07
@nkypy  Ok I finally got around to looking at this issue. The problem is that the primop version of gather (inside the embeding layer) is really inefficient. When you run with the CPUCompiler like so:
```rust
use luminal::prelude::*;
use luminal_cpu::CPUCompiler;
use luminal_nn::Embedding;

fn main() {
    let mut cx = Graph::new();
    let model: Embedding<65536, 1024> = Embedding::initialize(&mut cx);
    let input: GraphTensor<R2<1, 1>> = cx.tensor().set(vec![1., 1.]);
    let _output = model.forward(input);

    cx.compile(CPUCompiler::default(), ());
    cx.execute_debug();
}
```
the compiler is supposed to swap out the primop gather with an efficient cpu gather, but it wasn't finding it because of a bug in the compiler. Now it is fixed and should work. Can you rerun your example with the CPU compiler and verify it works correctly? You may want to use --release because initializing such a large embedding weight matrix will take a bit.

Once you verify it's fixed, I will close the issue

**Comment by nkypy** [comment] 2024-04-09 01:30
I rerun the example, and yes, it's fixed. thanks.

**Closed** 2024-04-09 11:52 UTC
